### ISSUE TITLE
More contrast when highlighting lines

### ISSUE THREAD

**Issue by wdkrnls** [fniessen/emacs-leuven-theme#16]
I often use `hl-line-flash` from the `hl-line+` package to orient myself in a buffer. I found the default leuven highlight color to be hard to see, so I replaced it with a bright red. Would that be reasonable change to make to the official color scheme, or do you feel strongly about the low contrast yellow?

**Comment by fniessen** [comment]
Sorry if I don't have that much time to look about it by myself, but why are you using `hl-line+` and not just the `global-hl-line-mode`?

Is `hl-line-flash` equal by default to `hl-line`?  If yes, I see no objection to give it a different value in my theme.

Regarding your question about my préférences, yes, I'd be strongly opposed to a strong highlighting of the current line (at least for me); I even doubt about using `hl-line-mode` at all!  Even if I still do use it for now...

But be aware that I'm very open to anything that can make my theme more open and/or attractable. Hence, maybe, some customization variables or such...

**Comment by fniessen** [comment]
I think I've improved the contrast of `highlight-line`. Though, I'm still interested in your answer to the above.

**Comment by wdkrnls** [comment]
Looking at the code for `hl-line-flash`, it just turns on `global-hl-line-mode` on the current line, waits  `hl-line-flash-show-period` seconds, and turns it off.

**Comment by dakrone** [comment]
@fniessen I think you recently added the underline to the `hl-line` correct? Is there a way to turn this off without manually setting the face? The problem is that it makes the underscores in any headline not show up:

With the line not on the headline:

![screen shot 2015-05-04 at 2 52 31 pm](https://cloud.githubusercontent.com/assets/19060/7462244/40dba11a-f26d-11e4-92cc-6a9dd1219e43.png)

With the line on the headline:

![screen shot 2015-05-04 at 2 52 24 pm](https://cloud.githubusercontent.com/assets/19060/7462252/4db1dd82-f26d-11e4-8ecc-5743f0abab7b.png)

(Notice that the underscores just don't show up due to the `hl-line` underline now)

**Comment by fniessen** [comment]
The above description is correct. It seems to depend, though, on specific fonts and/or specific sizes...

I've sent a bug report to the Emacs maintainers (emacs-bug#20510: Underscore hidden by underline). Wait and see...

I'd like it to be solved, because I like the underline in the current line.

Depending on the outcome, I'll either remove the underline, or add an option to be able to disable it.

**Comment by dakrone** [comment]
Thanks @fniessen :) judging from the response on the emacs-bugs mailing list, this isn't something that's fixable easily on the Emacs side. Would you be against adding an option to disable it?

**Comment by fniessen** [comment]
Regarding the underline attribute of `hl-line`, yep, simply disabled -- though I really think that it'd be a great additon, wouldn't it "remove" the underscores in some fonts / heights.

**Comment by fniessen** [comment]
@wdkrnls, I improved the contrast of the `hl-line` by default.

**Comment by stardiviner** [comment]
I have same question, hope @fniessen can add an option to disable this for a temporary solution.
