### ISSUE TITLE
leuven-theme

### ISSUE THREAD

**Issue by autosquid** [fniessen/emacs-leuven-theme#24]
Hi, this theme is fantastic and really catches my heart.
Do you have any plan to transplant it for zsh?

**Comment by fniessen** [comment]
Thanks a lot for your warming comments!

What do you mean by "transplanting to Zsh": better support for terminal environments?
Do you also mean on a dark background?

Anyway, no, I don't have any plans like that -- and very very few time (with a new job since 1 month!). Moreover, I don't use Emacs in terminals. That's something which I find too complex (in my Cygwin/Windows environment), so I'll guess I'll never have that need for myself...

Though, would you wanna work on it, I'd be glad to incorporate it in the theme.
