### ISSUE TITLE
How to find out if Emacs is using git Leuven or built-in leuven?

### ISSUE THREAD

**Issue by priyadarshan** [fniessen/emacs-leuven-theme#28]
I have been using the Emacs built-in Leuven as my default theme.

I would like to start using its latest version from this git repository. I have installed it and set up properly `custom-theme-load-path`, but how can one be sure the latest version is loaded instead of the built-in one?

Thank you for this very nice theme, it makes a big difference.

**Comment by fniessen** [comment]
To be honest, I don't know for sure, other than knowing that that font is looking good in the latest (Git) version, and wasn't in the old version that's built into Emacs.

Maybe `M-x locate-library RET leuven-theme` is answering that question, but I'm not sure whether it really is reliable -- it shows where it now would look first for loading the file, but maybe not what's really, currently loaded?

What your question suggests, as well, is that the built-in version in Emacs is a bit out-of-date. I should send a pull request, but this was not possible anymore a couple of weeks ago, because of the Emacs code freeze (for the future release). I'll try to do it soon.

**Comment by fniessen** [comment]
Maybe ask your question on gnu.emacs.help; this is interesting, for sure.

**Comment by priyadarshan** [comment]
I tried the `M-x locate-library` way but it does not help.
The way I devised it to make a significant change, like large font size, in the git library, restart Emacs and see if that shows up.
Thank you.

**Comment by MelleB** [comment]
You can use `M-x describe-theme`, select leuven and it shows you the file (leuven-theme.el).
If you open the file you can see which one it is.

**Comment by priyadarshan** [comment]
Simple and beautiful. Thank you so much.

**Comment by kshenoy** [comment]
> If you open the file you can see which one it is.

After opening the file, you can instead do `M-x pwd` to get the directory the theme is located in.
