### ISSUE TITLE
Inconsistencies in background for org-ellipsis

### ISSUE THREAD

**Issue by kshenoy** [fniessen/emacs-leuven-theme#33]
Hi, if I use a custom ellipsis for org-mode the background color also changes. 

This is what it looks like by default:

![default_ellipsis](https://cloud.githubusercontent.com/assets/1559554/20782407/cebe84e2-b748-11e6-847a-a9a728d13a3a.png)

and this is what it looks like if I change the ellipsis using `(setq org-ellipsis " ▼" )`

![custom_ellipsis](https://cloud.githubusercontent.com/assets/1559554/20782431/f01c5754-b748-11e6-9618-326dfa7a75d2.png)

Is there a way to instead change the background color to match the rest of the line?

P.S. Thanks for the excellent theme. I can't imagine using org-mode without it :)

**Comment by stardiviner** [comment]
What's font are you using?

**Comment by fniessen** [comment]
@stardiviner I'm using the nicest font I've found so far: Consolas (in my Cygwin Emacs on Windows). Though, it's not as wide as DejaVu, for example, but I can live with it.

@kshenoy I've always customized org-ellipsis as well -- see L7131 of my emacs-leuven.txt. And, since I've upgraded to Org 9, quite recently, I observe something similar to your screenshot, though a little bit better (The block is not per character). See https://www.screencast.com/t/qTjQVKE65lF. I guess this should be reported to Org-mode ML instead, then -- I don't see directly which face I could customize.

Wait, are you using emacs-leuven.el as well?  I know see that I've customized org-ellipsis's attributes in there (L 7125 of emacs-leuven.txt in its current state). I'll remove that, and use the same properties as the HideShow one, or none at all.

Wait, I now see I did customize org-ellipsis as well in emacs-leuven-theme. Let's remove it, and see...

Better, not really fine (underline property is there by default).

Let's customize it back. OK, better!
