### ISSUE TITLE
org-checkboxes strange colors

### ISSUE THREAD

**Issue by abcdw** [fniessen/emacs-leuven-theme#40]
https://github.com/fniessen/emacs-leuven-theme/blob/master/leuven-theme.el#L718

When line is selected checkbox status  become unreadable.
![screenshot from 2017-03-05 15-23-56](https://cloud.githubusercontent.com/assets/1218615/23587176/d3d4c658-01b7-11e7-8bd5-ab86837ad21b.png)

```
#123555
#E5F4FB
``` 
seems as a good choice for this colors

**Comment by fniessen** [comment]
You use the theme built in with Emacs, right?  Because, as of now, the white foreground is already replaced by a dark one...

The theme in Emacs should be updated, yes. If you want to use the new one, which evolves regularly, please consider using the one found on MELPA. That's the easiest way to get an up-to-date theme.
